/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'
import { RigidBody } from '@react-three/rapier'

type GLTFResult = GLTF & {
  nodes: {
    ingot: THREE.Mesh
  }
  materials: {}
}

export function Ingot(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ingot.glb') as unknown as GLTFResult
  return (
    <RigidBody type="dynamic" colliders="hull" name="ingot">
        <group {...props} dispose={null}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.ingot.geometry}
            material={nodes.ingot.material}
        />
        </group>
    </RigidBody>
  )
}

useGLTF.preload('/models/ingot.glb')
